# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Template Action'
description: 'Project Template for Deno GitHub Actions.'
author: 'Author'
branding:
  icon: 'award'
  color: 'green'

inputs:
  token:
    description: 'The GitHub token to use.'
    required: true

  organization-name:
    description: 'The name of the organization.'
    default: '${{ github.event.repository.owner.name }}'
    required: false

  only-public-repositories:
    description: 'Query only public repositories. Private repositories will be ignored.'
    default: 'true'
    required: false

  label-search-pattern:
    description: 'The category regex search pattern to use when searching for categories in the labels.'
    default: 'category'
    required: false

  categories-map:
    description: 'The category mapping. Can either be a YAML mapping or a path to a JSON file.'
    required: true

  categories-default:
    description: 'The default category that will be used if no category is found. If a JSON file is provided to the `categories` input, this value will be ignored.'
    required: false

outputs:
  categories-changed:
    description: 'If a category was added/changed/removed.'

runs:
  using: 'docker'
  image: 'docker://denoland/deno:latest'
  entrypoint: 'deno'
  args:
    - 'run'
    - '-A'
    - './src/index.ts'
